//
// Generated by `cargo run -p ephemeral-design`. Do not edit.
//
// The palette lives in crates/ephemeral-design/src/lib.rs, once, because
// two clients holding their own copies of a risk colour is two clients
// that will eventually disagree about how alarming a permission is.
// Every pairing in it is checked for contrast by that crate's tests.
//

import SwiftUI

/// Every colour Ephemeral draws, by the name it has on every platform.
enum Palette {
    /// the page itself
    static let ground = Color(red: 0.0431, green: 0.0549, blue: 0.0902)
    /// the page, one step lighter: gradients and inset areas
    static let groundSoft = Color(red: 0.0627, green: 0.0784, blue: 0.1216)
    /// somebody else's document, drawn on its own paper — white in both schemes, because a generated page does not know which one is in force and will use a browser's own black text
    static let paper = Color(red: 1.0000, green: 1.0000, blue: 1.0000)
    /// a card sitting on the page
    static let surface = Color(red: 0.0824, green: 0.1020, blue: 0.1569)
    /// something floating over it: a banner, a field, a menu
    static let surfaceHigh = Color(red: 0.1137, green: 0.1373, blue: 0.2039)
    /// a hairline that separates without drawing attention
    static let edge = Color(red: 0.1569, green: 0.1922, blue: 0.2863)
    /// the outline of something you can operate
    static let edgeStrong = Color(red: 0.3843, green: 0.4353, blue: 0.5647)
    /// what you are meant to read
    static let ink = Color(red: 0.9137, green: 0.9255, blue: 0.9608)
    /// supporting text: reasons, timestamps, counts
    static let inkQuiet = Color(red: 0.6510, green: 0.6863, blue: 0.7765)
    /// the quietest text that is still text
    static let inkFaint = Color(red: 0.5333, green: 0.5686, blue: 0.6588)
    /// Ephemeral itself: the primary action, and every focus ring
    static let accent = Color(red: 0.6549, green: 0.5451, blue: 0.9804)
    /// text on top of the accent
    static let accentInk = Color(red: 0.0431, green: 0.0549, blue: 0.0902)
    /// a ground tinted towards the accent
    static let accentSoft = Color(red: 0.1412, green: 0.1176, blue: 0.2706)
    /// low risk, and things that went well
    static let low = Color(red: 0.3098, green: 0.8392, blue: 0.6118)
    /// a ground tinted towards low risk
    static let lowSoft = Color(red: 0.0627, green: 0.1569, blue: 0.1255)
    /// medium risk, and anything that needs care but is not wrong
    static let medium = Color(red: 0.9412, green: 0.7059, blue: 0.3059)
    /// a ground tinted towards medium risk
    static let mediumSoft = Color(red: 0.1647, green: 0.1294, blue: 0.0627)
    /// high risk, and failures
    static let high = Color(red: 1.0000, green: 0.5647, blue: 0.3412)
    /// a ground tinted towards high risk
    static let highSoft = Color(red: 0.1804, green: 0.1020, blue: 0.0706)
    /// the permissions that can do the most damage
    static let critical = Color(red: 1.0000, green: 0.4784, blue: 0.5412)
    /// a ground tinted towards critical risk
    static let criticalSoft = Color(red: 0.1882, green: 0.0784, blue: 0.0980)

    /// The colour a lifecycle state is drawn in, by the kind of state it is.
    /// The engine's own vocabulary, so a phone cannot quietly decide a state is
    /// calmer than the window thinks it is.
    static func forState(_ kind: String) -> Color {
        switch kind {
        case "working": return accent
        case "awaitinguser": return medium
        case "active": return low
        case "attention": return high
        case "archived", "deleted": return inkFaint
        default: return inkQuiet
        }
    }

    /// The colour of a risk level. An unrecognised one is ordinary text, never
    /// green: guessing "low" about the widest permission Ephemeral offers is
    /// the one guess that does real harm.
    static func forRisk(_ level: String?) -> Color {
        switch level {
        case "low": return low
        case "medium": return medium
        case "high": return high
        case "critical": return critical
        default: return ink
        }
    }
}
